package cr.luparx.core.id;

import java.security.SecureRandom;
import java.util.UUID;

/**
 * RFC 9562 UUID version 7 generator (48-bit big-endian Unix epoch millisecond timestamp followed by
 * random bits). Identifiers are generated by the application (CONTRACT.md §5) so that:
 * <ul>
 *   <li>rows are roughly time-ordered, which keeps B-tree index inserts local, and</li>
 *   <li>no cross-tenant sequential counter is ever exposed (see SECURITY.md §4 on enumeration).</li>
 * </ul>
 * Thread-safe: {@link SecureRandom} is thread-safe and the class holds no mutable state.
 */
public final class Uuid7 {

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final long VERSION_7 = 0x7000L;
    private static final long VARIANT_RFC_4122 = 0x8000000000000000L;
    private static final long TIMESTAMP_MASK = 0x0000FFFFFFFFFFFFL;
    private static final long RAND_B_MASK = 0x3FFFFFFFFFFFFFFFL;

    private Uuid7() {
    }

    public static UUID generate() {
        return generate(System.currentTimeMillis());
    }

    /** Visible for testing and for deterministic backfills. */
    public static UUID generate(long unixMillis) {
        long mostSignificantBits = (unixMillis & TIMESTAMP_MASK) << 16;
        mostSignificantBits |= VERSION_7;
        mostSignificantBits |= RANDOM.nextInt(0x1000); // 12 bits of rand_a
        long leastSignificantBits = (RANDOM.nextLong() & RAND_B_MASK) | VARIANT_RFC_4122;
        return new UUID(mostSignificantBits, leastSignificantBits);
    }
}
