-- =============================================================================================
-- V1_0 — platform-core infrastructure tables.
--
-- Conventions applied to every migration (CONTRACT.md §5):
--   * primary keys are uuid values generated by the application (UUID v7, time-ordered)
--   * timestamps are timestamptz and always stored in UTC
--   * money would be amount_minor bigint + currency_code char(3) — never a floating-point type
--   * tables and non-obvious columns carry COMMENT ON so the schema documents itself
--
-- Audit and outbox rows are written here without foreign keys yet; the keys are added at the end of
-- V4_0, once `tenants` and `users` exist. They are append-only ledgers, so the constraint is about
-- referential correctness, not about lifecycle coupling.
-- =============================================================================================

-- Case-insensitive text, used for the email natural key (CONTRACT.md §5: `email citext UNIQUE`).
CREATE EXTENSION IF NOT EXISTS citext;

-- ---------------------------------------------------------------------------------------------
-- audit_events — append-only trail of every security- or business-relevant action (ADR 0013).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE audit_events (
    id              uuid        PRIMARY KEY,
    tenant_id       uuid,
    actor_user_id   uuid,
    actor_portal    varchar(16),
    action          varchar(64) NOT NULL,
    resource_type   varchar(64) NOT NULL,
    resource_id     varchar(128),
    ip_hash         varchar(64),
    user_agent      varchar(400),
    metadata        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    trace_id        varchar(64),
    occurred_at     timestamptz NOT NULL,
    CONSTRAINT ck_audit_events_portal
        CHECK (actor_portal IS NULL OR actor_portal IN ('CITIZEN', 'ADMIN', 'INSPECTOR', 'PLATFORM'))
);

COMMENT ON TABLE audit_events IS
    'Append-only audit trail. Never updated or deleted by the application (ADR 0013).';
COMMENT ON COLUMN audit_events.tenant_id IS
    'NULL only for platform-scoped actions; that null is itself the marker of a cross-tenant access.';
COMMENT ON COLUMN audit_events.ip_hash IS
    'SHA-256 of the client IP plus a per-deployment pepper. The address is never stored in clear.';
COMMENT ON COLUMN audit_events.metadata IS
    'Non-sensitive context only: never secrets, never full personal identifiers (SECURITY.md §11).';

CREATE INDEX ix_audit_events_tenant_occurred ON audit_events (tenant_id, occurred_at DESC);
CREATE INDEX ix_audit_events_actor_occurred  ON audit_events (actor_user_id, occurred_at DESC);
CREATE INDEX ix_audit_events_action_occurred ON audit_events (action, occurred_at DESC);

-- ---------------------------------------------------------------------------------------------
-- outbox_events — transactional outbox (ADR 0012).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE outbox_events (
    id              uuid        PRIMARY KEY,
    aggregate_type  varchar(64) NOT NULL,
    aggregate_id    varchar(64) NOT NULL,
    tenant_id       uuid,
    type            varchar(96) NOT NULL,
    payload         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL,
    published_at    timestamptz
);

COMMENT ON TABLE outbox_events IS
    'Events written in the same transaction as the state change they describe, published later by a relay.';
COMMENT ON COLUMN outbox_events.published_at IS
    'NULL means pending: the partial index below is the queue.';

-- Partial index: the relay only ever scans unpublished rows, so the index stays small forever.
CREATE INDEX ix_outbox_events_pending ON outbox_events (created_at) WHERE published_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- idempotency_keys — replay protection for sensitive writes (ADR 0012, CONTRACT.md §4).
-- ---------------------------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
    id               uuid         PRIMARY KEY,
    scope_hash       varchar(64)  NOT NULL,
    idempotency_key  varchar(200) NOT NULL,
    tenant_id        uuid,
    user_id          uuid,
    method           varchar(8)   NOT NULL,
    path             varchar(400) NOT NULL,
    request_hash     varchar(64)  NOT NULL,
    response_status  integer,
    response_body    text,
    created_at       timestamptz  NOT NULL,
    completed_at     timestamptz,
    expires_at       timestamptz  NOT NULL,
    CONSTRAINT uq_idempotency_keys_scope UNIQUE (scope_hash)
);

COMMENT ON TABLE idempotency_keys IS
    'One row per idempotent request. The unique index on scope_hash is what resolves concurrent '
    'retries across replicas — no in-memory coordination is involved.';
COMMENT ON COLUMN idempotency_keys.scope_hash IS
    'SHA-256 of (Idempotency-Key, user, method, path): the same key value from two users never collides.';
COMMENT ON COLUMN idempotency_keys.request_hash IS
    'SHA-256 of the request body. A replay with a different body is a client bug and answers 409.';

CREATE INDEX ix_idempotency_keys_expires ON idempotency_keys (expires_at);
